#!/bin/sh

commit_message=`cat "$1"`

prefixes=("Feature:" "Refactor:" "Fix:" "Hotfix:" "Doc:" "Lint:" "Merge")
max_length=75

if [ ${#commit_message} -gt $max_length ]; then
    echo "ERROR: Commit message must not exceed $max_length characters."
    exit 1
fi

if [ "${commit_message: -1}" == "." ]; then
    echo "ERROR: Commit message must not end with a period."
fi


for prefix in "${prefixes[@]}"; do
    if [[ $commit_message =~ ^$prefix ]]; then
        break
    fi
done

if [ $? -ne 0 ]; then
    echo "ERROR: Commit message must start with 'Feature:', 'Refactor:', 'Fix:', 'Hotfix:', 'Doc:', 'Lint:' or 'Merge'."
    exit 1
fi