BEGIN;

--
-- Create model User
--
CREATE TABLE
    "users_user" (
        "password" varchar(128) NOT NULL,
        "last_login" timestamp
        with
            time zone NULL,
            "is_superuser" boolean NOT NULL,
            "is_staff" boolean NOT NULL,
            "uuid" uuid NOT NULL PRIMARY KEY,
            "email" varchar(254) NOT NULL UNIQUE,
            "username" varchar(150) NOT NULL UNIQUE,
            "first_name" varchar(150) NOT NULL,
            "last_name" varchar(150) NULL,
            "date_joined" timestamp
        with
            time zone NOT NULL,
            "is_active" boolean NOT NULL,
            "profile_image" varchar(100) NULL
    );

CREATE TABLE
    "users_user_groups" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "user_id" uuid NOT NULL,
        "group_id" integer NOT NULL
    );

CREATE TABLE
    "users_user_user_permissions" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "user_id" uuid NOT NULL,
        "permission_id" integer NOT NULL
    );

CREATE INDEX "users_user_email_243f6e77_like" ON "users_user" ("email" varchar_pattern_ops);

CREATE INDEX "users_user_username_06e46fe6_like" ON "users_user" ("username" varchar_pattern_ops);

ALTER TABLE "users_user_groups" ADD CONSTRAINT "users_user_groups_user_id_group_id_b88eab82_uniq" UNIQUE ("user_id", "group_id");

ALTER TABLE "users_user_groups" ADD CONSTRAINT "users_user_groups_user_id_5f6f5a90_fk_users_user_uuid" FOREIGN KEY ("user_id") REFERENCES "users_user" ("uuid") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "users_user_groups" ADD CONSTRAINT "users_user_groups_group_id_9afc8d0e_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "users_user_groups_user_id_5f6f5a90" ON "users_user_groups" ("user_id");

CREATE INDEX "users_user_groups_group_id_9afc8d0e" ON "users_user_groups" ("group_id");

ALTER TABLE "users_user_user_permissions" ADD CONSTRAINT "users_user_user_permissions_user_id_permission_id_43338c45_uniq" UNIQUE ("user_id", "permission_id");

ALTER TABLE "users_user_user_permissions" ADD CONSTRAINT "users_user_user_permissions_user_id_20aca447_fk_users_user_uuid" FOREIGN KEY ("user_id") REFERENCES "users_user" ("uuid") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "users_user_user_permissions" ADD CONSTRAINT "users_user_user_perm_permission_id_0b93982e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "users_user_user_permissions_user_id_20aca447" ON "users_user_user_permissions" ("user_id");

CREATE INDEX "users_user_user_permissions_permission_id_0b93982e" ON "users_user_user_permissions" ("permission_id");

COMMIT;